### PR TITLE
Corrections and updates to the main text, data on DPPC Slipids and Charmm36-noNBFIX

### PR DESCRIPTION
**Pull request by jmelcr**
During reading the text of the manuscript (which is well written, btw) I noticed several mistakes and formulations I considered unambiguous. Here I provide possible corrections and improvements.

todo-s filled, Zenodo links added, scripts and data on my contributions included.

### CODE REVIEW

**Comment by ohsOllila** [comment]
I will merge this now since I agree with most changes. There are some things I want to comment, however, and I will soon make a commit about that.

**Comment by ohsOllila** [comment]
I did some changes and comments related to this in here https://github.com/NMRLipids/lipid_ionINTERACTION/commit/606f100bc6fd9b01be3ace40bc5fa9277bdca205

**Comment by jmelcr** [comment]
If you want to keep the result at the end of Intro, I'd state it a bit differently, so that it sounds more like a "grabber":
In this paper, We will show that the response of order parameters to penetrating cations 
is qualitatively correct in simulations, but the affinity of PC bilayers for Na$^{+}$ ions 
is significantly overestimated in several MD simulation models. 
Moreover, we will assay the accuracy of the tested models 
in the context of lipid--Ca$^{2+}$ interactions with atomistic resolution and their interpretation in NMR experiments.

**Comment by jmelcr** [comment]
I'd change a bit the line 412:
... quantitative response of alpha and beta segments ...

**Comment by ohsOllila** [comment]
Please check the concentrations you have reported in Table I and in file paths. Note that in this work we report the ion concentration as an ion concentration of the buffer used to solute the lipids, see equation in the caption of Table I. This is closest to the concentrations reported in the experimental data we are using.

**Comment by jmelcr** [comment]
Thank you for checking! It is really wrong -- looks like that either I did something wrong (selections in gmx ionize?) --or-- there might be a problem in gmx tool ionize itself. The numbers are correct when you count all_atoms/3 (i.e. also lipids). I trusted the software and just provided the desired concentration value and never checked it after that. The concentrations are then about 2.5x larger -- according to the equation they are: 
849, 1751 and 2574 for DPPC Slipids  --  does not change the interpretation of the results (just discard the too high concs.)
and 734 for POPC Charmm36 no-NBFIX  -- I'm afarid this changes a part of the discussion, behaves similarly to original Charmm36

Suggestion to others: double-check also other concentration values, if unsure.

**Comment by ohsOllila** [comment]
I think that gmx ionize just reports concentration calculated differently (total concentration in the box, not concentration in added buffer). One just have to be careful that the concentrations from different sources refer to the same concentration when comparing with different simulations and experiments . This is not the first time we have this issue in this project (last time I reported concentrations in the same way as you did now but other people like in the current manuscript). 

We just have to fix the concentrations in table and file paths now. Will you do this and make a pull request or should I do it?

I do not believe that the conclusions will change but let's put all the data in the figures and then we will see.

**Comment by ohsOllila** [comment]
I fixed the concentration of CHARMM36 simulation without NBFIX in commit https://github.com/NMRLipids/lipid_ionINTERACTION/commit/7a643b86566c228f91eab7046da609fa89cd135e

Slipid concentrations still to be done.

**Comment by ohsOllila** [comment]
Now I also fixed the Slipid concentrations and updated the discussion in commit https://github.com/NMRLipids/lipid_ionINTERACTION/commit/2f86b9ac11c7d9158cec9d28b779fd43c27cd702

There is one more thing: In the table it is written that for Slipids in 850mM the simulation was 100ns long and analysed also 100ns. Is this really the case? I think that there should be part of it left for equilibration.

**Comment by jmelcr** [comment]
I always use pre-equilibrated systems for production runs. Specyfying this looks almost outdated to me in nowadays papers. Add a value of about 5ns for equilibration.

**Comment by ohsOllila** [comment]
The density profiles for system with 850 mM NaCl looked a little bit weird. I did rerun the script and now they look reasonable. I added the the profile in the manuscript: https://github.com/NMRLipids/lipid_ionINTERACTION/commit/23930feed39fa09fbffa1b6a757193d29ee81588

**Pull request merged**
