### PR TITLE
Additional data for DPPC Slipids and POPC Charmm36 without NBFIX

### PR DESCRIPTION
**Pull request by jmelcr**
consistently with the simulation methods described in manuscripts, I ran several simulations to add some relevant data on DPPC with Slipids force field and for POPC with Charmm36 force field without using NBFIX terms.

### CODE REVIEW

**Comment by ohsOllila** [comment]
I did add these results in Figs. 2 and 6. I am still working with the results and discussion text. 
Please, check todo points 3, 7 and 8 in the manuscript.
Please, also add the density distributions (you can use e.g. https://github.com/NMRLipids/lipid_ionINTERACTION/blob/master/scripts/calcDENSITIES_SLIPID_1000mMscaled.sh and https://github.com/NMRLipids/lipid_ionINTERACTION/blob/master/scripts/calcDENSITIES_CHARMM_13na.sh).

**Comment by markussmiettinen** [comment]
Hi Pepa, great, thanks! It would be great if you could share the trajectories, e.g. via the [NMRlipids Zenodo community](https://zenodo.org/collection/user-nmrlipids?ln=en) so if someone else wants/needs to do analysis on these data, they can.

Also, when calculating the density distributions, one should be aware of the issue #4 (on smearing of the profiles, see my note there on 18feb2016).

**Comment by jmelcr** [comment]
I put it in my TODO...
Thanks for telling, I'll be careful with the centering..

**Comment by markussmiettinen** [comment]
Ok, great! The [centering script](https://github.com/NMRLipids/lipid_ionINTERACTION/commit/3e8d91b490506d87bede22dc38a8bd88c63730a0) I used does it in three steps: Make all molecules whole -> Center around one lipid tail CH3 to guarantee all lipids in the same box -> Center around the center of mass of all the g_3 carbons.

**Comment by jmelcr** [comment]
Before I proceed: Why is the [centering script](https://github.com/NMRLipids/lipid_ionINTERACTION/commit/3e8d91b490506d87bede22dc38a8bd88c63730a0) so complicated? I don't see a point in making that many transformations to the trajectory, when it looks like the last one alone is sufficient.

**Comment by markussmiettinen** [comment]
If your g_3 carbons are not all in the same periodic image(*) of your bilayer in all the snapshots along your trajectory, then centering around their center of mass (the last step) will not be sufficient.

(*) Along the (z) direction perpendicular to the membrane, in the xy the periodicity it of course does not matter.

**Comment by jmelcr** [comment]
Just a quick update -- I've got the density profiles. I elongated some simulations, where these profiles didn't look symmetric before (hence, some OrdParms will be refined-and-updated either). 
Now, I'll concentrate on the writing part and send it as one larger pull req.

**Pull request merged**
