### PR TITLE
067M CaCl2 CRM36 128POPC order and density; Sim. description and table

### PR DESCRIPTION
**Pull request by MykhailoGirych**
I analyzed last 100ns for order parameters and density. 
The file with simulation details and the file with table are in LibreOffice format. 
The table has the format of the paper. 

!!!!!!!!!!Do not merge the OrderParametersMATTI.dat file.
Data/POPC/NaCl/ULM/0na/OrderParametersMATTI.dat

### CODE REVIEW

**Comment by ohsOllila** [comment]
About citations:

I think that this one is not the correct one for the Amber ions:
[iii] Improved side-chain torsion potentials for the Amber ff99SB protein force field
Lindorff-Larsen et al., 2010
http://onlinelibrary.wiley.com/doi/10.1002/prot.22711/full

Why did you choose to cite this one when referring to the Verlet scheme:
[i] A flexible algorithm for calculating pair interactions on SIMD architectures.
Pall and Hess, 2013
http://www.sciencedirect.com/science/article/pii/S0010465513001975

**Comment by MykhailoGirych** [comment]
As for Verlet I just went to Gromacs cut-off schemes description:
http://www.gromacs.org/Documentation/Cut-off_schemes
There is the link to Pall and Hess article:
"For further information on algorithmic and implementation details of the Verlet cut-off scheme, drift tolerance and the MxN kernels, as well as detailed performance analysis, consult the following article: 
Páll, S. & Hess, B. A flexible algorithm for calculating pair interactions on SIMD architectures. Comput. Phys. Commun. 184, 2641–2650 (2013)."

I think you are right it is not the best article to cite. I guess the better option would be to cite "GROMACS 4.5: a high-throughput and highly parallel open source molecular simulation toolkit" because it's the first version where the Verlet algorithm was implemented in GROMACS. 
http://bioinformatics.oxfordjournals.org/content/early/2013/02/21/bioinformatics.btt055.full

Maybe it's even better to cite:
Swope WC, et al. A computer-simulation method for the calculation of equilibrium-constants for the formation of physical clusters of molecules: application to small water clusters. J. Chem. Phys. 1982;76:637-649.
(as you can see GROMACS guys cited that article)

As for Amber ions, I just chose the link to Amber ff article that  was mentioned in GROMACS pdb2gmx. Do you know the article where they developed the topologies for ions?

**Comment by ohsOllila** [comment]
I think that the current citation to Verlet scheme is ok.

About Amber ions, I do not know the correct reference. We have to dig it up.

**Comment by MykhailoGirych** [comment]
As for Amber ions according to the information from Sorin Lab website the ion parameters used in our simulations with AMBER are from AMBER-94 ff:
http://ffamber.cnsm.csulb.edu/ffamber.php#ffinfo
http://pubs.acs.org.sci-hub.io/doi/abs/10.1021/ja00124a002
Maybe we could just cite that AMBER-94 article?

**Comment by ohsOllila** [comment]
I cannot find the ion atom types or parameters from that article so I think that it is not the correct one to cite now.

**Comment by ohsOllila** [comment]
This one might contain some useful information: http://dx.doi.org/10.1021/jp0765392

**Comment by MykhailoGirych** [comment]
From the article that you mentioned:
"The AMBER-99 cation parameters are designated as being adapted from Åqvist (page 1).
The procedure for adaptation of Åqvist’s parameters is posted on the AMBER website (page 2):
http://ambermd.org/Questions/vdw.html"."
Maybe we could just cite the above stated link to the AMBER website and Åqvist’s paper (http://pubs.acs.org/doi/abs/10.1021/j100384a009)?

**Comment by ohsOllila** [comment]
Typically people cite in these cases only Åqvist. I think that this is enough.

**Comment by ohsOllila** [comment]
How about Ulmschneider simulations? Which ion parameters were used there?

**Comment by MykhailoGirych** [comment]
From the article ( http://pubs.acs.org.sci-hub.io/doi/pdf/10.1021/jp0765392 ):
"Recently,  we  showed  that  simulations  based  on  Åqvist’s original parameters for monovalent ions (as implemented in the OPLS forcefield) [9] reproduce with quantitative accuracy the ion pairing and clustering propensities in strong 1:1 electrolytes. [10]"

[9] - https://content.sakai.rutgers.edu/access/content/user/kparis/biomaps_513_references/02_B_01_JACS118_11225_OPLS.pdf
(this is just a general description of OPLS ff)

[10] - http://pubs.acs.org.sci-hub.io/doi/abs/10.1021/jp0708547
Here one could see that OPLS/AA ion parameters (used in Ulmschnider simulations) have been derived from Aqvist (Page 3, table).

Link to Aqvist:
http://pubs.acs.org/doi/abs/10.1021/j100384a009

**Pull request merged**
