### PR TITLE
details for simulation protocols + small suggestions in introduction/…

### PR DESCRIPTION
**Pull request by ClaireLoison**
…conclusion

### CODE REVIEW

**Comment by jmelcr** [comment]
Nice corrections.
In the paragraph corrected to "The apparent contradictions in the results ..." there's a short list of what might be wrong on the experimental side. It still might be worth mentioning (the correction omits it completely).

**Comment by ohsOllila** [comment]
There are changes suggested into introduction and conclusions because
"we cannot explain with this work how to reinterpret all the experimental  
data which seemed to sustain the Na+ binding. One tries to resolve the 
contradiction for MD results only."
However, I think that the explanations for the experimental data sustaining
Na+ binding are suggested in the manuscript. As discussed in the introduction,
the experiments suggesting strong Na+ binding are fluorescent probe, calorimetric
and AFM experiments (if there is more let me know). Their relation into other
experiments are discussed in the introduction, and then in the conclusions it
is written:
"The contradicting results from previous
molecular dynamics simulations [13, 14], fluorescent probe
dynamics [8, 10, 13], calorimetry [9, 13] and AFM [15–19],
suggesting stronger Na+ binding, can be explained by simulation
artefacts, direct interactions between Na+ and fluorescent
probes [12], alternative interpretations of the significance of
small phase transition temperature shifts [3], and insufficient
resolution of AFM."
The direct binding between Na+ and probes are explicitly discussed in ref. [12]. 
The interpretation of phase transition temperatures is in pages 334-335 in ref. [3]. 
I think that the resolution of AFM is not enough to overcome the spectroscopic evidence.

It also seems to me that the interpretations of strong binding in experiments 
are more or less inspired by the MD simulations showing strong binding.
This is, however, speculation based on the timeline of publications and 
personal discussions.

In conclusion, I think that based on our results combined with previous literature,
we can fairly suggest explanation also for previous experimental results.

If there is a way to nicely define the different ideas in the manuscript more precisely,
that would be, of course very good. For that, couple of comments on the suggested path:

"1) use the electrometer concept to define the NMR data as an absolute experimental reference of ion binding."
The electrometer concept as an absolute experimental reference of ion binding is quite
well experimentally defined in my opinion. Our results, of course, support this but this is 
not new information, in principle. I think that our main point is rather that
this can used for direct comparison of ion binding between simulations and experiments 
through order parameters, which has not been pointed out before (as far as I know).

"the electrometer concept is reproduced in MD for Na+, not really for Ca2+"
I think that our results very strongly indicate that the electrometer concept
is reproduced also for Ca2+. However, as discussed now more carefully in the manuscript,
in principle we cannot fully exclude the possibility that overestimated order parameter 
changes with CaCl_2 comes from oversensitive headgroups. 

"Different FF may give acceptable results in term of NMR data, therefore any molecular 
interpretation should be done with great care."
Now we do not differentiate between the three best models with Na+. However, I believe
that with long and careful simulations enough, we could see large enough differences
in order parameters to distinguish also between these models. Thus, I think that
the case that two models with different physical behaviour would give acceptable 
results in terms of NMR data is very unlikely when simulations are done carefully enough
(this is theoretically possible, of course).

If someone finds a way to nicely include this discussion in the text without complicating
too much, please go ahead.

**Comment by ClaireLoison** [comment]
Thanks Samuli for clarifying  in much details ! It's clearer to me now.

**Comment by ohsOllila** [comment]
Do you think that some parts especially need clarification in the manuscript?

**Comment by ClaireLoison** [comment]
Samuli, I have reread the article after your explanations, and actually, I find it indeed better
 without my suggestions !  Here small comments :

1) Maybe one could insist a bit in the conclusion on what you developed in your answer to me.
I reacted to the conclusion because the sentence   "The contradicting results from previous... and insufficient resolution of AFM. " is maybe  full of information and to me it seems vague but I understand it is basolutely not ! Maybe one could take one or two sentences more to clarify that  [3] and [12] already  proposed re-interpratations of previous experimental data. Maybe something  like :
" Concerning MD simulations,  we reinterpret strong Na+ binding as an inaccuracy of several simulation models, for example the Berger model used in [13,14]. Concerning experimental results, our  work sustains the views of  ... [3]  showing that small transition temperature shift could be interpretated by other phenomena  than Na+ binding, and  the work of ...  [12] proving that the results  of [8,10,13] could alternatively interprated by   direct interactions between Na+ and fluorescent probes."

2) One more  thought after re-reading, concerning the electrometer concept using cationic lipids 
(Figure 8 and appendix B) :
- Is the membrane charge  only described as  the lipid charge ? I would expect counter-ion binding,
  just as for zwitterionic membranes...comparing delta S directly as a function of lipid content, one assumes then that the Cl- binding on cationic membranes is well described by the model. maybe you can mention this assumption explicitely. Something like "one assumes that the description of Cl- binding is much less critical that Na+ binding" (why?) 
  - How to understand  the contradiction between the two experimental data (dotab and others), which one is the reference ? as the simulations considered as ok with experiments or overestimating the effect ? for me, the comparison with [31] is misleading for the discussion. I would only compare the PC/TAP mixture for exp. and simulations. 
- Maybe you can put vertical arrows on the figure 8 at the charge 0.34 e/lipid between exp and theoretical lines, to show what your 0.04 and 0.06 stand for. It took me a while to follow where these numbers come from... 

3) Figure 3 is mentioned after figure 4, not ? maybe put it in the order of appearance in the text. 

4)  a typo  "constants" in "However, there are some differences in the
proportionality constans"

5) a typo "presense" instead of "presence"  on top of page 9.

6) a typo "simulatios' on the bottom of page 8

7) in figure 2, the bottom right figure, i have the impression the symbols for the charmm yoo model should be open squares, but i see them as are open circles. I am not sure about that ! You might also put the exp. data in thicker lines, to distinguish them more than just with colors.

I find your discussion is very nice ! BR, Claire

**Comment by ohsOllila** [comment]
Thanks. I will now merge this pull request to include the changes which were not under discussion. Then I work back the content which was discussed, push it and then we can continue the discussion.

**Comment by ohsOllila** [comment]
I have now committed updates https://github.com/NMRLipids/lipid_ionINTERACTION/commit/0566aa3b84a691dc7a5692f31f36f9fe9fdd6ae0
Below are responses to Claire's comments.

1) The manuscript is now modified accordingly. The section in Conclusions now reads:
"In general, our results support the traditional (pre-2000) view that Na$^+$ and other monovalent ions (bar Li$^+$) do not specifically bind to the phospholipid bilayer at mM concentrations, in contrast to Ca$^{2+}$ and other multivalent ions~\cite{eisenberg79,akutsu81,altenbach84,tatulian87,cevc90,tocanne90,clarke99,binder02,pabst07,filippov09}. Concerning contradictions in the MD simulation results, we reinterpret strong Na$^+$ binding as an inaccuracy of several simulation models, for example the Berger model used in~\cite{bockmann03,bockmann04}. Concerning experimental results, our work sustains the views of Cevc~\cite{cevc90}, suggesting that small transition temperature shift could be interpretated by other phenomena than Na$^+$ binding, and the work of Filippov et al.~\cite{filippov09} proving that the results of~\cite{bockmann03,vacha09a,harb13} could be alternatively interprated by direct interactions between Na$^+$ and fluorescent probes. Finally, it is questionable if resolution of AFM experiments~\cite{manyes05,manyes06,fukuma07,ferber11,morata12} alone is sufficient to 
measure ion locations in fluidlike lipid bilayer systems."

It is good to optimize this since this may not be the last time when this raises some discussion.

2) This needs more attention. Discussion moved to https://github.com/NMRLipids/lipid_ionINTERACTION/issues/30

3) The Fig. 3 is actually mentioned already in Page 2 due to experimental data
"More specifically, the experimental data shown in Fig. 3 led to the relation..."

4) Fixed.

5) Fixed (this mistake was also elsewhere, all fixed).

6) Fixed.

7) Fixed.

**Comment by ohsOllila** [comment]
There is now a reply to point 2) in issue https://github.com/NMRLipids/lipid_ionINTERACTION/issues/30

We can continue discussion there.

**Pull request merged**
